### ISSUE TITLE
Un-decodable path throws 500

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#11017]
### Describe the problem and steps to reproduce it:

We see 500s in production that are caused by un-decodable paths. These generate noises to our alerting. Please return 404 if the frontend server can't decode them.

### What happened?
For example,

```
$ curl -I "https://addons-dev.allizom.org/en-US/firefox/%83/"
HTTP/2 500
content-type: text/html; charset=utf-8
content-length: 148
amo-request-id: 6fe35f2c-3e38-4be1-85a3-cddcc458cea1
cache-control: max-age=0
content-security-policy: default-src 'none'
date: Wed, 10 Nov 2021 19:13:50 GMT
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 0
vary: DNT,User-Agent,Accept-Encoding
x-cache: Error from cloudfront
via: 1.1 a02a98c09aaf2561c8ca019e473cf173.cloudfront.net (CloudFront)
x-amz-cf-pop: YVR50-C1
x-amz-cf-id: cg28y_YE_J0eqb4twcXCyUBcGa6oeRXFpf0Xw8cHDwTOwlYUwaY0Hg==
```

And the error in nodejs is this:

```
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: URIError: Pathname "/en-US/firefox/%83/" could not be decoded. This is likely caused by an invalid percent-encoding.
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at createLocation (/srv/node/node_modules/history/cjs/history.min.js:1:1741)
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at /srv/node/node_modules/history/cjs/history.min.js:1:9470
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at Array.map (<anonymous>)
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at createMemoryHistory (/srv/node/node_modules/history/cjs/history.min.js:1:9447)
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at _createHistory (/srv/code/src/amo/server/base.js:50:14)
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at /srv/code/src/amo/server/base.js:257:23
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at /srv/node/node_modules/express/lib/router/index.js:284:7
Nov 10 19:09:08 ip-172-31-45-211 docker-addons-frontend[23929]: at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
```

### What did you expect to happen?
404 instead of 500.

### Anything else we should know?
n/a

**Comment by willdurand** [comment]
This looks like a duplicate of https://github.com/mozilla/addons-frontend/issues/10061
