### ISSUE TITLE
Handle asyncConnect LOAD_FAIL errors better

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1521]
### Describe the problem and steps to reproduce it:

* Decorate a component with `asyncConnect`
* Add a callback with a typo that will throw an exception, such as `ReferenceError: store is not defined`

### What happened?

If you have `disableSSR: false` (the default, more like production), the page is a 500 and you see this unrelated error at the bottom of the server log:

````
[1] {"name":"server","app":"amo","hostname":"zenith.local","pid":6592,"level":50,"err":{"message":"Cannot read property 'status' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'status' of undefined\n    at /Users/kumar/dev/addons-frontend/src/core/server/base.js:213:31\n    at run (/Users/kumar/dev/addons-frontend/node_modules/core-js/modules/es6.promise.js:87:22)\n    at /Users/kumar/dev/addons-frontend/node_modules/core-js/modules/es6.promise.js:100:28\n    at flush (/Users/kumar/dev/addons-frontend/node_modules/core-js/modules/_microtask.js:18:9)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"},"msg":"Cannot read property 'status' of undefined","time":"2016-12-22T16:45:00.746Z","v":0}
```` 

The actual error was dispatched via redux as `LOAD_FAIL` and is buried in the log output:
````
[1] %c action color: #03A9F4; font-weight: bold { type: '@redux-conn/LOAD_FAIL',
[1]   payload:
[1]    { key: 'initialData',
[1]      error:
[1]       ReferenceError: store is not defined
[1]           at /Users/kumar/dev/addons-frontend/src/amo/components/AddonReviewList.js:88:27
[1]           at run (/Users/kumar/dev/addons-frontend/node_modules/core-js/modules/es6.promise.js:87:22)
[1]           at /Users/kumar/dev/addons-frontend/node_modules/core-js/modules/es6.promise.js:100:28
[1]           at flush (/Users/kumar/dev/addons-frontend/node_modules/core-js/modules/_microtask.js:18:9)
[1]           at _combinedTickCallback (internal/process/next_tick.js:67:7)
[1]           at process._tickCallback (internal/process/next_tick.js:98:9) } }
````

If you have `disableSSR: true` which is more convenient for frontend development, you see the same `LOAD_FAIL` action in the console but your component will be rendered anyway, just without the property that the `asyncConnect` callback usually gives you (when successful). This will probably cause an additional error to be thrown in your component because of the undefined property.

### What did you expect to happen?

This is all pretty confusing. We should fix it for both the production and development case.

### Anything else we should know?

I think I hate isomorphic web apps. Or maybe they hate me? Or maybe I just hate `asyncConnect`? I do not want my heart to be filled with hate.

**Comment by muffinresearch** [comment]
Not in production - seems to be tricky to repro.
