### ISSUE TITLE
https://addons-dev.allizom.org/en-GB/firefox/ is a 500

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1558]
### Describe the problem and steps to reproduce it:

* With the mamo cookie set to view the mobile site.
* Visit https://addons-dev.allizom.org/en-GB/firefox/ 

### What happened?

* the en-GB locale results in a 500 error.

### What did you expect to happen?

* No 500
* Note that the disco pane renders OK.

**Comment by muffinresearch** [comment]
Here's the traceback:

```
[1]     Error: Cannot find module '../moment'
[1]         at Function.Module._resolveFilename (module.js:469:15)
[1]         at Function._module2.default._resolveFilename (/Users/Whatevs/code/addons-frontend/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:423:34)
[1]         at Function.module._load (/Users/Whatevs/code/addons-frontend/node_modules/piping/lib/launcher.js:24:23)
[1]         at Module.require (module.js:497:17)
[1]         at require (internal/module.js:20:19)
[1]         at /Users/Whatevs/code/addons-frontend/src/locale/en_GB/amo.js:70:51
[1]         at Object.anonymous [as _momentDefineLocale] (/Users/Whatevs/code/addons-frontend/src/locale/en_GB/amo.js:68:3)
[1]         at makeI18n (/Users/Whatevs/code/addons-frontend/src/core/i18n/utils.js:192:18)
[1]         at /Users/Whatevs/code/addons-frontend/src/core/server/base.js:207:24
[1]
```

**Comment by muffinresearch** [comment]
Looks like the try/catch might be better inside the function here: https://github.com/mozilla/addons-frontend/blob/162d46fed3e3283e3c973ec4abedd55d45496535/bin/build-locales#L57

**Comment by tofumatt** [comment]
Disco pane doesn't use moment locales inside its locale files so doesn't have that require. Strange, I thought I had that aliased so it wouldn't cause this error. I'll investigate.

**Comment by muffinresearch** [comment]
> Disco pane doesn't use moment locales inside its locale files so doesn't have that require. Strange, I thought I had that aliased so it wouldn't cause this error. I'll investigate.

This only occurs for amo not the disco pane as noted in the initial report.
