### ISSUE TITLE
404s are 500s

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1616]
Go to http://127.0.0.1:3000/en-US/firefox/404/, should be a 404 but instead it's a 500. 

The trace is:

```
Error: No LandingPage content for addonType: 404
[1]         at LandingPageBase.contentForType (/Users/Whatevs/code/addons-frontend/src/amo/components/LandingPage.js:77:11)
[1]         at LandingPageBase.render (/Users/Whatevs/code/addons-frontend/src/amo/components/LandingPage.js:85:23)
[1]         at /Users/Whatevs/code/addons-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
[1]         at measureLifeCyclePerf (/Users/Whatevs/code/addons-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
[1]         at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/Whatevs/code/addons-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
[1]         at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/Whatevs/code/addons-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
[1]         at ReactCompositeComponentWrapper.performInitialMount (/Users/Whatevs/code/addons-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
[1]         at ReactCompositeComponentWrapper.mountComponent (/Users/Whatevs/code/addons-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
[1]         at Object.mountComponent (/Users/Whatevs/code/addons-frontend/node_modules/react-dom/lib/ReactReconciler.js:46:35)
[1]         at ReactCompositeComponentWrapper.performInitialMount (/Users/Whatevs/code/addons-frontend/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
```

**Comment by muffinresearch** [comment]
This blocks https://bugzilla.mozilla.org/show_bug.cgi?id=1330939

**Comment by tofumatt** [comment]
Shoot, this is because of the URLs we have setup where that hits a landing page. I'm on this.

**Comment by tofumatt** [comment]
Gonna wait until #1541 is merged of there will be annoying conflicts, but this should be pretty straightforward.

**Comment by muffinresearch** [comment]
@tofumatt would be good to fix this as soon as possible since it might not help for fixing up the fallback pages bug.

**Comment by tofumatt** [comment]
Ten four; I was gonna do it along with our better error handling as I'm not exactly clear on how to throw a 404 from inside a component yet but I'll figure that out I guess 😄
