### ISSUE TITLE
Configure SENTRY_DSN on dev/stage/prod

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1886]
In order to hook up our error reporting (https://github.com/mozilla/addons-frontend/issues/1559) we need the `SENTRY_DSN` environment variable declared in dev/stage/prod for all front-end applications: amo, discopane, and admin. This DSN should be the same one [used by addons-server](https://github.com/mozilla/addons-server/blob/master/src/olympia/conf/dev/settings.py#L228).

**Comment by jasonthomas** [comment]
Shouldn't we use a different SENTRY_DSN  (which means a new project) for each app/env combination? I've set it up that way thinking that would be ideal, but just want to verify.

That being said, I didn't receive any tracebacks when hitting the /simulate-error/ endpoint. I need to look into further why tracebacks are not coming through to sentry.

**Comment by kumar303** [comment]
Sure, whatever makes sense for the dsn. The simulate error view should also
log to the console which may help to figure out if it's working.

**Comment by jasonthomas** [comment]
I need assistance debugging the sentry integration, `raven test SENTRY_DSN` works but /simulate-error/ route from the app are not coming through into sentry [1].

I noticed that `app.use(Raven.requestHandler());` is not configured, do we need that here? I patched -dev but didn't seem to do anything useful [2]

Also [2] mentions that the request and error handler needs to be used before another other middleware, I tried to see if DEBUG=express:* would show anything useful and looks like others might be loaded first? 

```
Feb 27 16:55:30 ip-172-31-39-205 docker[18866]: npm info ok
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "x-powered-by" to true
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "etag" to 'weak'
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "etag fn" to [Function: wetag]
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "env" to 'dev'
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "query parser" to 'extended'
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "query parser fn" to [Function: parseExtendedQueryString]
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "subdomain offset" to 2
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "trust proxy" to false
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "trust proxy fn" to [Function: trustNone]
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application booting in dev mode
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "view" to [Function: View]
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "views" to '/srv/code/views'
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "jsonp callback name" to 'callback'
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:application set "x-powered-by" to false
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: {"name":"server","app":"disco","hostname":"ip-172-31-39-205","pid":142,"level":30,"msg":"raven configured","time":"2017-02-27T16:55:35.462Z","v":0}
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / query
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / expressInit
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / <anonymous>
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / <anonymous>
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / logRequests
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / hsts
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / frameguard
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / nosniff
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / xXssProtection
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / csp
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:route new /__version__
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /__version__
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:route get /__version__
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:route new /__cspreport__
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /__cspreport__
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:route post /__cspreport__
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / prefixMiddleWare
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / <anonymous>
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / <anonymous>
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router:layer new /
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: {"name":"server","app":"disco","hostname":"ip-172-31-39-205","pid":142,"level":30,"msg":"🔥  Addons-frontend server is running [ENV:dev] [APP:disco] [isDevelopment:false] [isDeployed:true] [apiHost:https://addons-dev.allizom.org] [apiPath:/api/v3]","time":"2017-02-27T16:55:35.477Z","v":0}
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: {"name":"server","app":"disco","hostname":"ip-172-31-39-205","pid":142,"level":30,"msg":"👁  Open your browser at http://0.0.0.0:4000 to view it.","time":"2017-02-27T16:55:35.477Z","v":0}
Feb 27 16:55:35 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 16:55:35 GMT express:router use / query
```

If you need a test sentry DSN test please let me know, I will provision one for you.

[1] https://sentry.prod.mozaws.net/operations/addons-frontend-disco-dev/issues/384447/
[2] https://docs.sentry.io/clients/node/integrations/express/

**Comment by jasonthomas** [comment]
Also here is the output when I make a request to /simulate-error/

```
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router dispatching GET /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router query  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router expressInit  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router <anonymous>  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router <anonymous>  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router logRequests  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router hsts  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router frameguard  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router nosniff  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router xXssProtection  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router csp  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router prefixMiddleWare  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Mon, 27 Feb 2017 17:25:34 GMT express:router <anonymous>  : /en-US/firefox/simulate-error/
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: {"name":"server","app":"disco","hostname":"ip-172-31-39-205","pid":142,"level":30,"msg":"Replacing lang in URL en-US -> en-US","time":"2017-02-27T17:25:34.098Z","v":0}
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: {"name":"server","app":"disco","hostname":"ip-172-31-39-205","pid":142,"level":30,"req":{"method":"GET","url":"/en-US/firefox/simulate-error/","headers":{"host":"discovery.addons-dev.allizom.org:4000","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.5","cache-control":"no-cache","cookie":"sessionid=\".eJwNyNENgDAIBcBdmADoK7UuY4qFBeyHiXF3vc97KO9xXGusoJ1gKsBssYkFq0j_B26Aq7B4Y0XppY42e5yI7g1pkswprrPS-wF-LRWc:1cYHuz:2T2FLV4I3pnpv-wNJrc5m_sp66s\"","dnt":"1","pragma":"no-cache","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0","x-forwarded-protocol":"ssl","x-real-ip":"68.195.65.157","x-scheme":"http","x-forwarded-for":"68.195.65.157, 172.31.6.238","x-forwarded-port":"4000","x-forwarded-proto":"http","connection":"keep-alive"},"remoteAddress":"172.31.53.188","remotePort":54069},"res":{"statusCode":200,"header":null},"start":"2017-02-27T17:25:34.097Z","finish":"2017-02-27T17:25:34.099Z","elapsed":2,"msg":"","time":"2017-02-27T17:25:34.100Z","v":0}
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: {"name":"server","app":"disco","hostname":"ip-172-31-39-205","pid":142,"level":30,"msg":"Simulating an error","time":"2017-02-27T17:25:34.104Z","v":0}
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: {"name":"server","app":"disco","hostname":"ip-172-31-39-205","pid":142,"level":50,"err":{"message":"This is a simulated error","name":"Error","stack":"Error: This is a simulated error\n    at exports.default (/srv/code/src/core/containers/SimulateError.js:6:9)\n    at /srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:306:16\n    at measureLifeCyclePerf (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)\n    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:305:14)\n    at ReactCompositeComponentWrapper._constructComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:280:21)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactDOMComponent.mountChildren (/srv/node/node_modules/react-dom/lib/ReactMultiChild.js:238:44)\n    at ReactDOMComponent._createContentMarkup (/srv/node/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)\n    at ReactDOMComponent.mountComponent (/srv/node/node_modules/react-dom/lib/ReactDOMComponent.js:520:29)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReco
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: nciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-dom/lib/ReactReconciler.js:46:35)\n    at /srv/node/node_modules/react-dom/lib/ReactServerRendering.js:45:36\n    at ReactServerRenderingTransaction.perform (/srv/node/node_modules/react-dom/lib/Transaction.js:140:20)\n    at renderToStringImpl (/srv/node/node_modules/react-dom/lib/ReactServerRendering.js:43:24)\n    at Object.renderToString (/srv/node/node_modules/react-dom/lib/ReactServerRendering.js:73:10)\n    at ServerHtml.render (/srv/code/src/core/containers/ServerHtml.js:82:42)\n    at /srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21\n    at measureLifeCyclePerf (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)\n    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)\n    at ReactCompositeComponentWrapper._renderValidatedComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)\n    at ReactCompositeComponentWrapper.performInitialMount (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)\n    at ReactCompositeComponentWrapper.mountComponent (/srv/node/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)\n    at Object.mountComponent (/srv/node/node_modules/react-do
Feb 27 17:25:34 ip-172-31-39-205 docker[18866]: m/lib/ReactReconciler.js:46:35)\n    at /srv/node/node_modules/react-dom/lib/ReactServerRendering.js:45:36\n    at ReactServerRenderingTransaction.perform (/srv/node/node_modules/react-dom/lib/Transaction.js:140:20)\n    at renderToStringImpl (/srv/node/node_modules/react-dom/lib/ReactServerRendering.js:43:24)\n    at Object.renderToString (/srv/node/node_modules/react-dom/lib/ReactServerRendering.js:73:10)\n    at hydrateOnClient (/srv/code/src/core/server/base.js:237:31)\n    at /srv/code/src/core/server/base.js:286:18\n    at process._tickDomainCallback (internal/process/next_tick.js:129:7)"},"msg":"This is a simulated error","time":"2017-02-27T17:25:34.108Z","v":0}
```

**Comment by kumar303** [comment]
Whoops, I think the problem was that I didn't define the error handler at the end. I also added the missing request handler middleware, thanks. Can you check Sentry again once this has deployed to dev? https://github.com/mozilla/addons-frontend/pull/1925

**Comment by jasonthomas** [comment]
\o/ looks like they are coming through now https://sentry.prod.mozaws.net/operations/addons-frontend-disco-dev/issues/384467/ Thanks! I need to make more one more change to the SENTRY_DSN before I can call this closed.

**Comment by jasonthomas** [comment]
SENTRY_DSN configured on all apps/envs.
