### ISSUE TITLE
TypeError: addon is undefined on DetailPage

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2175]
From Sentry: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/386032/

We're getting `addon is undefined` in [the call to `addon.guid`](https://github.com/mozilla/addons-frontend/blob/790b8b5e710a8be79085249bfaf7f7a01caddc0b/src/amo/containers/DetailPage.js#L23):
````js
const installation = state.installations[addon.guid] || { status: UNKNOWN };
```` 

Stack trace:
````
TypeError: r is undefined
  at mapState(./src/amo/containers/DetailPage.js:23:8)
  at this(~/react-redux/lib/components/connect.js:155:0)
  at this(~/react-redux/lib/components/connect.js:142:0)
  at this(~/react-redux/lib/components/connect.js:204:0)
  at inst(~/react-redux/lib/components/connect.js:340:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:799:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:822:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:362:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactMultiChild.js:238:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:653:0)
  at internalInstance(~/react-dom/lib/ReactDOMComponent.js:520:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactMultiChild.js:238:0)
  at this(~/react-dom/lib/ReactDOMComponent.js:653:0)
  at internalInstance(~/react-dom/lib/ReactDOMComponent.js:520:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at internalInstance(~/react-dom/lib/ReactCompositeComponent.js:258:0)
  at ReactReconciler(~/react-dom/lib/ReactReconciler.js:46:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:371:0)
  at this(~/react-dom/lib/ReactCompositeComponent.js:258:0)
````

**Comment by muffinresearch** [comment]
This needs re-evaluating if it's still a problem. If it's not that common we can downgrade the priority.

**Comment by muffinresearch** [comment]
I can't find this in Sentry any more https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/?query=is%3Aunresolved+addon+is+undefined

**Comment by kumar303** [comment]
I think this fixed it https://github.com/mozilla/addons-frontend/commit/6b01159fe2#diff-4953c6065645080e8ab07f343314c395L294
