### ISSUE TITLE
Test suite is failing depending on the locale

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#2945]
### Describe the problem and steps to reproduce it:

Run: `yarn run test-once`

### What happened?

On my laptop, I have two failing test cases related to the `i18n` module:

```
Summary of all failing tests
 FAIL  tests/unit/core/i18n/test_utils.js
  ● i18n utils › makeI18n › falls-back to number.toLocaleString if Intl is not an object

    expect(received).toEqual(expected)

    Expected value to equal:
      "1,234"
    Received:
      "1.234"

      at Object.<anonymous> (tests/unit/core/i18n/test_utils.js:464:41)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● i18n utils › makeI18n › falls-back to number.toLocaleString when Intl is missing a NumberFormat constructor

    expect(received).toEqual(expected)

    Expected value to equal:
      "12,345"
    Received:
      "12 345"

      at Object.<anonymous> (tests/unit/core/i18n/test_utils.js:474:41)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)


Test Suites: 1 failed, 136 passed, 137 total
Tests:       2 failed, 1584 passed, 1586 total
```

### What did you expect to happen?

All green 💚

**Comment by willdurand** [comment]
cc @tofumatt
