### ISSUE TITLE
addons-frontend docker image fails to build.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#4582]
The integration-test job on addons-server are [failing](https://circleci.com/gh/mozilla/addons-server)

Trying to run the steps locally results in the log below.

```
addons-frontend_1   | yarn run v1.5.1
addons-frontend_1   | $ bin/build-checks.js && better-npm-run build '&&' yarn start
addons-frontend_1   | running better-npm-run in /srv/code
addons-frontend_1   | Executing script: build
addons-frontend_1   |
addons-frontend_1   | to be executed: npm run clean && npm run version-check && npm run build-locales && webpack --bail --verbose --display-error-details --progress --colors --config webpack.prod.config.babel.js && yarn start
addons-frontend_1   |
addons-frontend_1   | > mozilla-addons-frontend@0.0.1 clean /srv/code
addons-frontend_1   | > rimraf './dist/*!(.gitkeep)' './webpack-assets.json' './src/locale/**(!.gitkeep)'
addons-frontend_1   |
addons-frontend_1   |
addons-frontend_1   | > mozilla-addons-frontend@0.0.1 version-check /srv/code
addons-frontend_1   | > bin/version-check.js
addons-frontend_1   |
addons-frontend_1   |
addons-frontend_1   | > mozilla-addons-frontend@0.0.1 build-locales /srv/code
addons-frontend_1   | > bin/build-locales
addons-frontend_1   |
addons-frontend_1   | No moment i18n available for ast; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for bn_BD; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for cak; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for dbl; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for dbr; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for dsb; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for fy_NL; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for ga_IE; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for hsb; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for kab; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for mn; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for nb_NO; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for nn_NO; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for pt_PT; consider adding one or creating a mapping.
addons-frontend_1   | No moment i18n available for sv_SE; consider adding one or creating a mapping.
addons-frontend_1   |  95% emitting[ ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: ValidationError: PostCSS Loader Invalid Options
addons-frontend_1   |
addons-frontend_1   |   options['outputStyle'] is an invalid additional property
addons-frontend_1   |   options['sourceMapContents'] is an invalid additional property
addons-frontend_1   |
addons-frontend_1   |       at runLoaders (/srv/node/node_modules/webpack/lib/NormalModule.js:195:19)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:364:11
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:230:18
addons-frontend_1   |       at runSyncOrAsync (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
addons-frontend_1   |       at iterateNormalLoaders (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:202:4
addons-frontend_1   |       at /srv/node/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
addons-frontend_1   |       at _combinedTickCallback (internal/process/next_tick.js:73:7)
addons-frontend_1   |       at process._tickCallback (internal/process/next_tick.js:104:9)
addons-frontend_1   |       at runLoaders (/srv/node/node_modules/webpack/lib/NormalModule.js:195:19)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:364:11
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:179:20
addons-frontend_1   |       at context.callback (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
addons-frontend_1   |       at /srv/node/node_modules/extract-text-webpack-plugin/dist/loader.js:119:16
addons-frontend_1   |       at compile (/srv/node/node_modules/webpack/lib/Compiler.js:300:11)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compiler.js:510:14)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:202:11)
addons-frontend_1   |       at Compiler.<anonymous> (/srv/node/node_modules/extract-text-webpack-plugin/dist/loader.js:112:7)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:204:14)
addons-frontend_1   |       at Compiler.<anonymous> (/srv/node/node_modules/webpack/lib/CachePlugin.js:78:5)
addons-frontend_1   |       at Compiler.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:206:13)
addons-frontend_1   |       at compilation.seal.err (/srv/node/node_modules/webpack/lib/Compiler.js:507:11)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:677:19)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:668:11)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:202:11)
addons-frontend_1   |       at Compilation.<anonymous> (/srv/node/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:206:13)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:663:10)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsyncSeries (/srv/node/node_modules/webpack/lib/Compilation.js:659:9)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at Compilation.seal (/srv/node/node_modules/webpack/lib/Compilation.js:602:8)
addons-frontend_1   |       at applyPluginsParallel.err (/srv/node/node_modules/webpack/lib/Compiler.js:504:17)
addons-frontend_1   |       at /srv/node/node_modules/tapable/lib/Tapable.js:289:11
addons-frontend_1   |       at _addModuleChain (/srv/node/node_modules/webpack/lib/Compilation.js:505:11)
addons-frontend_1   |       at processModuleDependencies.err (/srv/node/node_modules/webpack/lib/Compilation.js:475:14)
addons-frontend_1   |       at _combinedTickCallback (internal/process/next_tick.js:73:7)
addons-frontend_1   |       at process._tickCallback (internal/process/next_tick.js:104:9),
addons-frontend_1   |   ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: ValidationError: PostCSS Loader Invalid Options
addons-frontend_1   |
addons-frontend_1   |   options['outputStyle'] is an invalid additional property
addons-frontend_1   |   options['sourceMapContents'] is an invalid additional property
addons-frontend_1   |
addons-frontend_1   |       at runLoaders (/srv/node/node_modules/webpack/lib/NormalModule.js:195:19)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:364:11
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:230:18
addons-frontend_1   |       at runSyncOrAsync (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
addons-frontend_1   |       at iterateNormalLoaders (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:202:4
addons-frontend_1   |       at /srv/node/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
addons-frontend_1   |       at _combinedTickCallback (internal/process/next_tick.js:73:7)
addons-frontend_1   |       at process._tickCallback (internal/process/next_tick.js:104:9)
addons-frontend_1   |       at runLoaders (/srv/node/node_modules/webpack/lib/NormalModule.js:195:19)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:364:11
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:179:20
addons-frontend_1   |       at context.callback (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
addons-frontend_1   |       at /srv/node/node_modules/extract-text-webpack-plugin/dist/loader.js:119:16
addons-frontend_1   |       at compile (/srv/node/node_modules/webpack/lib/Compiler.js:300:11)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compiler.js:510:14)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:202:11)
addons-frontend_1   |       at Compiler.<anonymous> (/srv/node/node_modules/extract-text-webpack-plugin/dist/loader.js:112:7)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:204:14)
addons-frontend_1   |       at Compiler.<anonymous> (/srv/node/node_modules/webpack/lib/CachePlugin.js:78:5)
addons-frontend_1   |       at Compiler.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:206:13)
addons-frontend_1   |       at compilation.seal.err (/srv/node/node_modules/webpack/lib/Compiler.js:507:11)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:677:19)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:668:11)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:202:11)
addons-frontend_1   |       at Compilation.<anonymous> (/srv/node/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:206:13)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:663:10)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsyncSeries (/srv/node/node_modules/webpack/lib/Compilation.js:659:9)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at Compilation.seal (/srv/node/node_modules/webpack/lib/Compilation.js:602:8)
addons-frontend_1   |       at applyPluginsParallel.err (/srv/node/node_modules/webpack/lib/Compiler.js:504:17)
addons-frontend_1   |       at /srv/node/node_modules/tapable/lib/Tapable.js:289:11
addons-frontend_1   |       at _addModuleChain (/srv/node/node_modules/webpack/lib/Compilation.js:505:11)
addons-frontend_1   |       at processModuleDependencies.err (/srv/node/node_modules/webpack/lib/Compilation.js:475:14)
addons-frontend_1   |       at _combinedTickCallback (internal/process/next_tick.js:73:7)
addons-frontend_1   |       at process._tickCallback (internal/process/next_tick.js:104:9),
addons-frontend_1   |   ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: ValidationError: PostCSS Loader Invalid Options
addons-frontend_1   |
addons-frontend_1   |   options['outputStyle'] is an invalid additional property
addons-frontend_1   |   options['sourceMapContents'] is an invalid additional property
addons-frontend_1   |
addons-frontend_1   |       at runLoaders (/srv/node/node_modules/webpack/lib/NormalModule.js:195:19)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:364:11
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:230:18
addons-frontend_1   |       at runSyncOrAsync (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
addons-frontend_1   |       at iterateNormalLoaders (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
addons-frontend_1   |       at Array.<anonymous> (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
addons-frontend_1   |       at Storage.finished (/srv/node/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
addons-frontend_1   |       at /srv/node/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
addons-frontend_1   |       at /srv/node/node_modules/graceful-fs/graceful-fs.js:78:16
addons-frontend_1   |       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
addons-frontend_1   |       at runLoaders (/srv/node/node_modules/webpack/lib/NormalModule.js:195:19)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:364:11
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:179:20
addons-frontend_1   |       at context.callback (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
addons-frontend_1   |       at /srv/node/node_modules/extract-text-webpack-plugin/dist/loader.js:119:16
addons-frontend_1   |       at compile (/srv/node/node_modules/webpack/lib/Compiler.js:300:11)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compiler.js:510:14)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:202:11)
addons-frontend_1   |       at Compiler.<anonymous> (/srv/node/node_modules/extract-text-webpack-plugin/dist/loader.js:112:7)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:204:14)
addons-frontend_1   |       at Compiler.<anonymous> (/srv/node/node_modules/webpack/lib/CachePlugin.js:78:5)
addons-frontend_1   |       at Compiler.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:206:13)
addons-frontend_1   |       at compilation.seal.err (/srv/node/node_modules/webpack/lib/Compiler.js:507:11)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:677:19)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:668:11)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:202:11)
addons-frontend_1   |       at Compilation.<anonymous> (/srv/node/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:206:13)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:663:10)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsyncSeries (/srv/node/node_modules/webpack/lib/Compilation.js:659:9)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at Compilation.seal (/srv/node/node_modules/webpack/lib/Compilation.js:602:8)
addons-frontend_1   |       at applyPluginsParallel.err (/srv/node/node_modules/webpack/lib/Compiler.js:504:17)
addons-frontend_1   |       at /srv/node/node_modules/tapable/lib/Tapable.js:289:11
addons-frontend_1   |       at _addModuleChain (/srv/node/node_modules/webpack/lib/Compilation.js:505:11)
addons-frontend_1   |       at processModuleDependencies.err (/srv/node/node_modules/webpack/lib/Compilation.js:475:14)
addons-frontend_1   |       at _combinedTickCallback (internal/process/next_tick.js:73:7)
addons-frontend_1   |       at process._tickCallback (internal/process/next_tick.js:104:9),
addons-frontend_1   |   ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: ValidationError: PostCSS Loader Invalid Options
addons-frontend_1   |
addons-frontend_1   |   options['outputStyle'] is an invalid additional property
addons-frontend_1   |   options['sourceMapContents'] is an invalid additional property
addons-frontend_1   |
addons-frontend_1   |       at runLoaders (/srv/node/node_modules/webpack/lib/NormalModule.js:195:19)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:364:11
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:230:18
addons-frontend_1   |       at runSyncOrAsync (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
addons-frontend_1   |       at iterateNormalLoaders (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
addons-frontend_1   |       at Array.<anonymous> (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
addons-frontend_1   |       at Storage.finished (/srv/node/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
addons-frontend_1   |       at /srv/node/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
addons-frontend_1   |       at /srv/node/node_modules/graceful-fs/graceful-fs.js:78:16
addons-frontend_1   |       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
addons-frontend_1   |       at runLoaders (/srv/node/node_modules/webpack/lib/NormalModule.js:195:19)
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:364:11
addons-frontend_1   |       at /srv/node/node_modules/loader-runner/lib/LoaderRunner.js:179:20
addons-frontend_1   |       at context.callback (/srv/node/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
addons-frontend_1   |       at /srv/node/node_modules/extract-text-webpack-plugin/dist/loader.js:119:16
addons-frontend_1   |       at compile (/srv/node/node_modules/webpack/lib/Compiler.js:300:11)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compiler.js:510:14)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:202:11)
addons-frontend_1   |       at Compiler.<anonymous> (/srv/node/node_modules/extract-text-webpack-plugin/dist/loader.js:112:7)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:204:14)
addons-frontend_1   |       at Compiler.<anonymous> (/srv/node/node_modules/webpack/lib/CachePlugin.js:78:5)
addons-frontend_1   |       at Compiler.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:206:13)
addons-frontend_1   |       at compilation.seal.err (/srv/node/node_modules/webpack/lib/Compiler.js:507:11)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:677:19)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:668:11)
addons-frontend_1   |       at next (/srv/node/node_modules/tapable/lib/Tapable.js:202:11)
addons-frontend_1   |       at Compilation.<anonymous> (/srv/node/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:206:13)
addons-frontend_1   |       at applyPluginsAsync.err (/srv/node/node_modules/webpack/lib/Compilation.js:663:10)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at applyPluginsAsyncSeries (/srv/node/node_modules/webpack/lib/Compilation.js:659:9)
addons-frontend_1   |       at Compilation.applyPluginsAsyncSeries (/srv/node/node_modules/tapable/lib/Tapable.js:195:46)
addons-frontend_1   |       at Compilation.seal (/srv/node/node_modules/webpack/lib/Compilation.js:602:8)
addons-frontend_1   |       at applyPluginsParallel.err (/srv/node/node_modules/webpack/lib/Compiler.js:504:17)
addons-frontend_1   |       at /srv/node/node_modules/tapable/lib/Tapable.js:289:11
addons-frontend_1   |       at _addModuleChain (/srv/node/node_modules/webpack/lib/Compilation.js:505:11)
addons-frontend_1   |       at processModuleDependencies.err (/srv/node/node_modules/webpack/lib/Compilation.js:475:14)
addons-frontend_1   |       at _combinedTickCallback (internal/process/next_tick.js:73:7)
addons-frontend_1   |       at process._tickCallback (internal/process/next_tick.js:104:9) ]
addons-frontend_1   | error An unexpected error occurred: "Command failed.
addons-frontend_1   | Exit code: 1
addons-frontend_1   | Command: sh
addons-frontend_1   | Arguments: -c bin/build-checks.js && better-npm-run build '&&' yarn start
addons-frontend_1   | Directory: /srv/code
addons-frontend_1   | Output:
addons-frontend_1   | ".
addons-frontend_1   | info If you think this is a bug, please open a bug report with the information provided in "/srv/code/yarn-error.log".
addons-frontend_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
addonsserver_addons-frontend_1 exited with code 1
```

**Comment by willdurand** [comment]
@jrbenny35 why is this issue not closed?

**Comment by willdurand** [comment]
The BC break has been reverted in upstream lib, closing this issue now. Travis CI should catch such an issue since it also builds the `amo` and `disco` apps. Unfortunately, I cannot find a PR with the `postcss-loader` upgrade to `2.1.2`. I guess the build on addons-server occurred before we got the Greenkeeper PR and before we got a failing Travis error.
