### ISSUE TITLE
No spacing between 'featured' badge and theme preview in Theme details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4626]
Follow up for #4520 

STR:

1. Log in to AMO and select a featured theme to view it's details page (i.e. https://addons.allizom.org/en-GB/firefox/addon/dew-on-spider-web/?src=featured)
2. Observe the position of the featured label

Actual result:
There is no spacing between the featured badge and theme preview

Expected result:
Some space should be present between the featured badge and the theme preview

Notes:
- reproduced on AMO-stage, FF59 Win10x64

![image](https://user-images.githubusercontent.com/31961530/37768083-0faa4fd2-2dd5-11e8-966a-14567f59a4bd.png)

**Comment by svitlana-galianova** [comment]
Hello, I would like to help out with this one.

**Comment by svitlana-galianova** [comment]
I am trying to access this link (http://localhost:3000/en-GB/firefox/addon/dew-on-spider-web/?src=featured) while running amo locally (I tried both amo:stage and amo:dev), but I keep getting this error:
Maybe I am doing something wrong or missing some step?
```
[1]  Error: Error calling: /api/v3/accounts/profile/ (status: 500)
[1]     at createApiError (/.../addons-frontend/src/core/api/index.js:59:20)
[1]     at /.../addons-frontend/src/core/api/index.js:189:24
[1]     at <anonymous>
[1]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[1] [2018-03-28T15:37:02.561Z] ERROR: server/86882 on mac...: Caught error during rendering: Error: Error calling: /api/v3/accounts/profile/ (status: 500) (app=amo)
[1] [2018-03-28T15:37:02.561Z] ERROR: server/86882 on mac...: Showing 500 page for error: Error: Error calling: /api/v3/accounts/profile/ (status:500) (app=amo)
[1] [2018-03-28T15:37:02.562Z] ERROR: server/86882 on mac...: Error calling: /api/v3/accounts/profile/ (status: 500) (app=amo)
[1]     Error: Error calling: /api/v3/accounts/profile/ (status: 500)
[1]         at createApiError (/.../addons-frontend/src/core/api/index.js:59:20)
[1]         at /.../addons-frontend/src/core/api/index.js:189:24
[1]         at <anonymous>
[1]         at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[1] Warning: Failed prop type: The prop `component` is marked as required in `ServerHtml`, but its value is `undefined`.
[1]     in ServerHtml
[2] [2018-03-28T15:37:02.567Z]  INFO: proxy/86875 on mac...: 500 ~> http://127.0.0.1:3333/en-GB/firefox/addon/dew-on-spider-web/?src=featured (app=amo)
```

**Comment by svitlana-galianova** [comment]
I have started amo:dev and it solved that issue for me

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/38238674-4a5042f6-3733-11e8-9872-5eadcf1b5329.png)
