### ISSUE TITLE
UnhandledPromiseRejectionWarning in production

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6367]
### Describe the problem and steps to reproduce it:

I read the production logs.

### What happened?

I saw:

```
(node:201) UnhandledPromiseRejectionWarning: URIError: Pathname "/en-US/android/collections/mozilla%df%27/privacy-matters/" could not be decoded. This is likely caused by an invalid percent-encoding.
 at createLocation (/srv/node/node_modules/history/LocationUtils.js:51:13)
 at /srv/node/node_modules/history/createMemoryHistory.js:57:74
 at Array.map (<anonymous>)
 at createMemoryHistory (/srv/node/node_modules/history/createMemoryHistory.js:56:32)
 at createHistory (/srv/code/src/core/server/base.js:44:14)
 at _callee$ (/srv/code/src/core/server/base.js:281:21)
 at tryCatch (/srv/node/node_modules/regenerator-runtime/runtime.js:65:40)
 at Generator.invoke [as _invoke] (/srv/node/node_modules/regenerator-runtime/runtime.js:303:22)
 at Generator.prototype.(anonymous function) [as next] (/srv/node/node_modules/regenerator-runtime/runtime.js:117:21)
 at step (/srv/code/src/core/server/base.js:113:191)
 at /srv/code/src/core/server/base.js:113:437
 at new Promise (<anonymous>)
 at /srv/code/src/core/server/base.js:113:99
 at /srv/code/src/core/server/base.js:243:3
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at trailingSlashesMiddleware (/srv/code/src/core/middleware/trailingSlash.js:48:10)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at prefixMiddleware (/srv/code/src/core/middleware/prefixMiddleware.js:144:10)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at csp (/srv/node/node_modules/helmet-csp/index.js:59:7)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at xXssProtection (/srv/node/node_modules/x-xss-protection/index.js:26:7)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at nosniff (/srv/node/node_modules/dont-sniff-mimetype/index.js:4:5)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at frameguard (/srv/node/node_modules/frameguard/index.js:38:5)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at hsts (/srv/node/node_modules/hsts/index.js:42:5)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at logRequests (/srv/code/src/core/middleware/logRequests.js:7:3)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at responseTime (/srv/node/node_modules/response-time/index.js:61:5)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at /srv/node/node_modules/raven/lib/client.js:560:9
 at bound (domain.js:303:14)
 at runBound (domain.js:314:12)
 at Raven.context (/srv/node/node_modules/raven/lib/client.js:431:33)
 at ravenRequestMiddleware (/srv/node/node_modules/raven/lib/client.js:557:12)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at expressInit (/srv/node/node_modules/express/lib/middleware/init.js:40:5)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at query (/srv/node/node_modules/express/lib/middleware/query.js:45:5)
 at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
 at /srv/node/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
 at next (/srv/node/node_modules/express/lib/router/index.js:275:10)
 at Function.handle (/srv/node/node_modules/express/lib/router/index.js:174:3)
 at Function.handle (/srv/node/node_modules/express/lib/application.js:174:10)
 at Server.app (/srv/node/node_modules/express/lib/express.js:39:9)
 at emitTwo (events.js:126:13)
 at Server.emit (events.js:214:7)
 at parserOnIncoming (_http_server.js:634:12)
 at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
 (node:201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

### What did you expect to happen?

No unhandled promise in production code, ever.

### Anything else we should know?

I don't know whether this is hyper-critical, but it looks quite bad.

**Comment by willdurand** [comment]
Related issue (maybe): https://github.com/ReactTraining/history/issues/619

**Comment by willdurand** [comment]
Also see: https://github.com/ReactTraining/history/issues/505
