### ISSUE TITLE
Import errors when running tox in Python 2

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6503]
When running `tox` locally I am getting a couple import errors.

**Comment by willdurand** [comment]
what kind of errors? could it be related to a recent python deps update PR? I run tox quite often and did not get any issues.. last time was < 1 week

**Comment by kumar303** [comment]
Example:

```
Traceback (most recent call last):
  File "/Users/kumar/dev/addons-frontend/.tox/discopane-ui-tests/bin/pytest", line 7, in <module>
    from pytest import main
  File "/Users/kumar/dev/addons-frontend/.tox/discopane-ui-tests/lib/python2.7/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
  File "/Users/kumar/dev/addons-frontend/.tox/discopane-ui-tests/lib/python2.7/site-packages/_pytest/config/__init__.py", line 18, in <module>
    import _pytest._code
  File "/Users/kumar/dev/addons-frontend/.tox/discopane-ui-tests/lib/python2.7/site-packages/_pytest/_code/__init__.py", line 3, in <module>
    from .code import Code  # noqa
  File "/Users/kumar/dev/addons-frontend/.tox/discopane-ui-tests/lib/python2.7/site-packages/_pytest/_code/code.py", line 11, in <module>
    from _pytest.compat import _PY2, _PY3, PY35, safe_str
  File "/Users/kumar/dev/addons-frontend/.tox/discopane-ui-tests/lib/python2.7/site-packages/_pytest/compat.py", line 47, in <module>
    from pathlib2 import Path, PurePath
ImportError: No module named pathlib2
```

These were all the packages missing for me: https://github.com/mozilla/addons-frontend/pull/6504/files

I think it's because I was running Python 2.7, not 3.6 (like TravisCI). However, Python 2.7 ships with mac, right? So we should probably support it. As far as I can tell, adding the new dependencies doesn't break Python 3. I *do* have Python 3 installed but tox isn't using it for some reason.

@willdurand do you not have Python 2.7 installed? Also, this is an interesting type of holiday you take in Germany 👀

**Comment by kumar303** [comment]
I think `tox` is using the default interpreter (the one `tox` was installed with). I guess we should preserve that feature which means making our `tox` work in either Python 2 or 3.

**Comment by kumar303** [comment]
Yep, it looks like this change was forward compatible with Python 3.

**Comment by willdurand** [comment]
I would not waste time on python 2, but if it's a matter of updating the requirements. txt, that's fine I guess.

**Comment by kumar303** [comment]
I've brew unlinked and relinked python (which is at 3.7) and I'm still not sure why the old tox is on my path -- it's definitely pointing to the 2.7 lib. Weird. Anyway, I think it's nice when things just work out of the box and these extra requirements seem harmless. Thanks for reviewing the patch.
