### ISSUE TITLE
`yarn storybook-build` is broken

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6955]
### Describe the problem and steps to reproduce it:

1. Run `yarn storybook-build`

### What happened?

```
❯ yarn storybook-build
yarn run v1.12.3
$ better-npm-run storybook-build
running better-npm-run in /Users/williamdurand/projects/mozilla/addons-frontend
Executing script: storybook-build

to be executed: build-storybook -c stories/setup
info @storybook/react v3.4.10
info
info => Loading custom .babelrc
info => Loading custom addons config.
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "webpackServerHost" is not defined
    at Config.get (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/Users/williamdurand/projects/mozilla/addons-frontend/webpack.dev.config.babel.js:32:28)
    at Module._compile (module.js:652:30)
    at loader (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/williamdurand/projects/mozilla/addons-frontend/stories/setup/webpack.config.babel.js:2:1)
    at Module._compile (module.js:652:30)
    at loader (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/williamdurand/projects/mozilla/addons-frontend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What did you expect to happen?

No error.

### Anything else we should know?

The `gh-pages` branch has not been update since October 15, 2018. I suppose that's broken since then. We have no output on Travis CI for this job, so hard to tell...

**Comment by willdurand** [comment]
Do not worry about it, I can also give it a look. I plan to look into the webpack4 migration too, because that's likely needed for code-splitting -_-

**Comment by ioanarusiczki** [comment]
@willdurand Is this "qa not nedded" or perhaps there's something to check on?

**Comment by willdurand** [comment]
> @willdurand Is this "qa not nedded" or perhaps there's something to check on?

ah sorry, it is indeed a "qa: not needed"
