### ISSUE TITLE
Make logs more readable for development

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#826]
The webpack server logs are hard to read. This is what an exception looks like:

```
[1] {"name":"server","app":"disco","hostname":"zenith.local","pid":11187,"level":50,"err":{"message":"last.apply is not a function","name":"TypeError","stack":"TypeError: last.apply is not a function\n    at v (/Users/kumar/dev/addons-frontend/node_modules/redux/lib/compose.js:33:19)\n    at /Users/kumar/dev/addons-frontend/node_modules/redux/lib/applyMiddleware.js:51:63\n    at createStore (/Users/kumar/dev/addons-frontend/node_modules/redux/lib/createStore.js:65:33)\n    at createStore (store.js:12:10)\n    at base.js:114:21\n    at /Users/kumar/dev/addons-frontend/node_modules/react-router/lib/match.js:65:5\n    at /Users/kumar/dev/addons-frontend/node_modules/react-router/lib/createTransitionManager.js:118:11\n    at done (/Users/kumar/dev/addons-frontend/node_modules/react-router/lib/AsyncUtils.js:79:19)\n    at /Users/kumar/dev/addons-frontend/node_modules/react-router/lib/AsyncUtils.js:85:7\n    at getComponentsForRoute (/Users/kumar/dev/addons-frontend/node_modules/react-router/lib/getComponents.js:15:5)"},"msg":"","time":"2016-07-25T14:31:17.681Z","v":0}
[1] {"name":"server","app":"disco","hostname":"zenith.local","pid":11187,"level":30,"req":{"method":"GET","url":"/en-US/firefox/discovery/pane/48.0/Darwin/normal","headers":{"host":"127.0.0.1:3000","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US","accept-encoding":"gzip, deflate","connection":"keep-alive","upgrade-insecure-requests":"1"},"remoteAddress":"127.0.0.1","remotePort":60292},"res":{"statusCode":500,"header":"HTTP/1.1 500 Internal Server Error\r\nStrict-Transport-Security: max-age=31536000\r\nX-Frame-Options: DENY\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nContent-Security-Policy-Report-Only: default-src 'none'; base-uri 'self'; child-src 'none'; connect-src 'self' https://addons-dev-cdn.allizom.org 127.0.0.1:3001; form-action 'none'; frame-src 'none'; img-src 'self' 127.0.0.1:3001; media-src https://addons-discovery.cdn.mozilla.net; object-src 'none'; script-src 'self' https://addons-dev-cdn.allizom.org 127.0.0.1:3001; style-src 'self' blob:; report-uri /__cspreport__\r\nDate: Mon, 25 Jul 2016 14:31:17 GMT\r\nConnection: keep-alive\r\nContent-Length: 21\r\n\r\n"},"start":"2016-07-25T14:31:17.678Z","finish":"2016-07-25T14:31:17.681Z","elapsed":3,"msg":"","time":"2016-07-25T14:31:17.681Z","v":0}
```

It would be nicer to see a formatted stack trace, maybe even with colors!

**Comment by muffinresearch** [comment]
It should be possible to run the logs through the bunyan binary. That will then provide nicer formatting. I did try this the other day but it appears not to work, possibly because of the other output on startup.

See https://github.com/trentm/node-bunyan#cli-usage for more info.

**Comment by muffinresearch** [comment]
I feel like we need to clean up logs wholesale. 

I think something else in the output is preventing bunyan from working. Even though it's supposed to just pass-through other content. I got it working by sending bunyan logs to a file and reading them back in via the CLI.

Even with this though the logs are very noisy due to the request logging. I think we should work out a scheme and push all log output to files instead. We could potentially divert the request logging seprately somehow.

We might find it's possible to fix things by putting all the redux related logging through our own logging infrastructure.

@jasonthomas would it work ok for you if we moved to sending logs to a logs dir in the root of the project or is there anything else we need to think about?

**Comment by jasonthomas** [comment]
I think it would be okay to send logs to the a log directory in the root of a project. Operationally for our dev, stage and prod envs we would need need to attach a host directory into the container so that we could maintain and process the logs outside the container.

Ideally we would like to continue using stderr/stdout for logging. Our new ops logging pipeline uses this method (via systemd-journal) to parse logs and push them into nice places like kibana.

**Comment by muffinresearch** [comment]
@jasonthomas thanks for the info. If the status quo is still good for you we can just do something different only in development or fix the bunyan tool and make sure we can filter the noise appropriately with that instead.

**Comment by kumar303** [comment]
It's really convenient to get logs in stdout during development all in one server-startup command. Otherwise you'd have to tail a file. Just a minor annoyance.

I haven't looked too closely but maybe the leading whitespace in the output is tripping up the bunyan binary?

**Comment by muffinresearch** [comment]
This was already fixed here: https://github.com/mozilla/addons-frontend/blob/master/package.json#L68
