### ISSUE TITLE
Integration-test error: You cannot submit a Mozilla signed extension

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#9777]
```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/landfill/management/commands/generate_default_addons_for_frontend.py", line 94, in handle
    serializer.create_installable_addon()
  File "/code/src/olympia/landfill/serializers.py", line 443, in create_installable_addon
    create_version_for_upload(
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/code/src/olympia/devhub/tasks.py", line 113, in create_version_for_upload
    parsed_data = parse_addon(upload, addon, user=upload.user)
  File "/code/src/olympia/files/utils.py", line 1114, in parse_addon
    parsed = parse_xpi(pkg, addon, minimal=minimal, user=user)
  File "/code/src/olympia/files/utils.py", line 1007, in parse_xpi
    return check_xpi_info(xpi_info, addon, xpi, user=user)
  File "/code/src/olympia/files/utils.py", line 1081, in check_xpi_info
    raise forms.ValidationError(
django.core.exceptions.ValidationError: ['You cannot submit a Mozilla Signed Extension']
make: *** [Makefile-docker:170: setup-ui-tests] Error 1
```

Seems like fxa is working again but this error is new. Any insight here?

**Comment by wagnerand** [comment]
Should be fixed by https://github.com/mozilla/addons-server/pull/15765

**Comment by diox** [comment]
Fix was merged in `addons-server` `master` branch (https://github.com/mozilla/addons-server/commit/bc49ae6850e0a073d108567d8499c0aebb48f9db), sorry about that.
